#include "share/atspre_define.hats"
#include "share/atspre_staload.hats"
staload "libats/SATS/athread.sats"
staload "libats/SATS/deqarray.sats"
staload _ = "libats/DATS/deqarray.dats"
staload UN = "prelude/SATS/unsafe.sats"
staload _ = "libats/DATS/athread.dats"
staload _ = "libats/DATS/athread_posix.dats"
// staload "./../SATS/channel.sats"
